name: Build and deploy dev

on:
  workflow_dispatch:
    inputs:
      push_test_image:
        type: boolean
        default: false
        description: Push test image

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    secrets:
      GH_ACTIONS_ROLE_ARN: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
      ARTIFACT_SOURCE_BUCKET_NAME: ${{ secrets.DEV_ARTIFACT_SOURCE_BUCKET_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      ECR_REPOSITORY: ${{ secrets.DEV_ECR_REPOSITORY }}
      TEST_ECR_REPOSITORY: ${{ secrets.DEV_TEST_ECR_REPOSITORY }}
    with:
      PUSH_TEST_IMAGE: ${{ inputs.push_test_image || false }}
