name: Deploy to build and promote

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  deploy-build-and-promote:
    uses: ./.github/workflows/deploy.yml
    secrets:
      GH_ACTIONS_ROLE_ARN: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
      ARTIFACT_SOURCE_BUCKET_NAME: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      TEST_ECR_REPOSITORY: ${{ secrets.TEST_ECR_REPOSITORY }}
    with:
      PUSH_TEST_IMAGE: true
