name: Integration test

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  integration-test:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8001:8000

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: .nvmrc

      - name: Install dependencies (tests)
        run: npm ci
        working-directory: tests/ui-tests

      - name: Get Playwright version
        id: playwright-version
        working-directory: tests/ui-tests
        run: echo "version=$(npx playwright --version)" >> $GITHUB_OUTPUT

      - name: Cache browsers
        id: cache-browsers
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install browsers
        if: ${{ steps.cache-browsers.outputs.cache-hit != 'true' }}
        run: npm run install-browsers
        working-directory: tests/ui-tests

      - name: Run integration tests
        run: npm run test:integration

      - name: Run UI tests
        working-directory: tests/ui-tests
        run: |
          touch .env
          echo "PRE_OR_POST_DEPLOY=pre" >> .env
          echo "PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/" >> .env
          npm run test
