name: Validation

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  validation-checks:
    name: Validation checks
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint and Prettier
        run: npm run lint

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93

      - name: Lint Terraform
        run: npm run tflint

      # TODO: add cfnlint, and SAM validate
